---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: copy local uploads directory to remote
      copy:
        src: "{{ playbook_dir }}/../../web/uploads"
        dest: "{{ vhost_path }}/shared/web"
        owner: www-data
        group: www-data
