---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: copy local upload images directory to local
      synchronize:
        mode: push
        recursive: yes
        perms: yes
        times: yes
        src: "{{ playbook_dir }}/../../web/media/image"
        dest: "{{ vhost_path }}/shared/web/media"
    - name: fix ownership in remote uploaded files
      file:
        path: "{{ vhost_path }}/shared/web/media"
        recurse: yes
        follow: yes
        owner: www-data
        group: www-data
