services:
    # Students
    admin.student:
        class: AppBundle\Admin\StudentAdmin
        arguments: [ ~, AppBundle\Entity\Student, AppBundle:Admin\StudentAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Alumne", group: "Alumnes" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Student/edit.html.twig" ] ]

    admin.parent:
        class: AppBundle\Admin\PersonAdmin
        arguments: [ ~, AppBundle\Entity\Person, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Pare, mare o tutor", group: "Alumnes" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Student/edit.html.twig" ] ]

    # Teachers
    admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [ ~, AppBundle\Entity\Teacher, AppBundle:Admin\TeacherAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Professor", group: "Professors" }

    admin.teacher_absence:
        class: AppBundle\Admin\TeacherAbsenceAdmin
        arguments: [ ~, AppBundle\Entity\TeacherAbsence, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Absència", group: "Professors" }

    # Classrooms
    admin.class_group:
        class: AppBundle\Admin\ClassGroupAdmin
        arguments: [ ~, AppBundle\Entity\ClassGroup, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Grup", group: "Aules" }
        calls:
            - [ setTemplate, [ edit, "::Admin/ClassGroup/edit.html.twig" ] ]

    admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [ ~, AppBundle\Entity\Event, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Horari", group: "Aules" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Event/edit.html.twig" ] ]

    # Billings
    admin.tariff:
        class: AppBundle\Admin\TariffAdmin
        arguments: [ ~, AppBundle\Entity\Tariff, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tarifa", group: "Facturació" }

    admin.invoice:
        class: AppBundle\Admin\InvoiceAdmin
        arguments: [ ~, AppBundle\Entity\Invoice, AppBundle:Admin\InvoiceAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Factura", group: "Facturació" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Invoice/edit.html.twig" ] ]
            - [ setTemplate, [ list, "::Admin/Invoice/list.html.twig" ] ]

    admin.billing.invoice_line:
        class: AppBundle\Admin\InvoiceLineAdmin
        arguments: [ ~, AppBundle\Entity\InvoiceLine, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Línies", group: "Facturació", show_in_dashboard: false }

    # Services
    admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~, AppBundle\Entity\Service, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servei", group: "Serveis" }

    # Contacts
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Messatge de contacte", group: "Contactes" }

    admin.newslettercontact:
        class: AppBundle\Admin\NewsletterContactAdmin
        arguments: [ ~, AppBundle\Entity\NewsletterContact, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Butlletí de contacte", group: "Contactes" }

    # Configurations
    admin.province:
        class: AppBundle\Admin\ProvinceAdmin
        arguments: [ ~, AppBundle\Entity\Province, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Administració" }

    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [ ~, AppBundle\Entity\City, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ciutat", group: "Administració" }

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Administració" }

    admin.bank:
        class: AppBundle\Admin\BankAdmin
        arguments: [ ~, AppBundle\Entity\Bank, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Bank", group: "Administració", show_in_dashboard: false }
