imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: "pdo_sqlite"
        path:   "%kernel.root_dir%/databases/test.db3"

liip_functional_test:
    cache_sqlite_db: true
    authentication:
        username: "%private_admin_test_user%"
        password: "%private_admin_test_pass%"

security:
    firewalls:
        admin:
            http_basic: ~
