imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: [ 'email' ]
    handlers:
        email:
            type:     stream
            path:     "%kernel.logs_dir%/emails.log"
            level:    info
            channels: [ 'email' ]
        main:
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%.log"
            level:    debug
            channels: [ '!event' ]
        console:
            type:     console
            channels: [ '!event', '!doctrine' ]

assetic:
    use_controller: true

swiftmailer:
    delivery_address: "%mailer_destination%"

cypress_git_elephant:
    enable_profiler: false
    profiler_repository_path: "%kernel.root_dir%/../"
    repositories:
        "BoxIdiomes": "%kernel.root_dir%/../"
