services:
# Sonata Admin
    admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [ ~ , AppBundle\Entity\Teacher, ~ , "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Teacher", group: "Teachers" }
    admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~ , AppBundle\Entity\Service, ~ , "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Service", group: "Services" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "User", group: "Users" }
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge de Contacte", group: "Contacts" }

# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
