services:
# Sonata Admin
    admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [ ~ , AppBundle\Entity\Teacher, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Teacher", group: "Teachers" }
