services:
# Sonata Admin
    # students
    admin.student:
        class: AppBundle\Admin\StudentAdmin
        arguments: [ ~, AppBundle\Entity\Student, AppBundle:Admin\StudentAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Alumne", group: "Alumnes" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Student/edit.html.twig" ] ]
    admin.parent:
        class: AppBundle\Admin\PersonAdmin
        arguments: [ ~, AppBundle\Entity\Person, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Pare, mare o tutor", group: "Alumnes" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Student/edit.html.twig" ] ]
    # teachers
    admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [ ~, AppBundle\Entity\Teacher, AppBundle:Admin\TeacherAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Professor", group: "Professors" }
    admin.teacher_absence:
        class: AppBundle\Admin\TeacherAbsenceAdmin
        arguments: [ ~, AppBundle\Entity\TeacherAbsence, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Absència", group: "Professors" }
    # classrooms
    admin.class_group:
        class: AppBundle\Admin\ClassGroupAdmin
        arguments: [ ~, AppBundle\Entity\ClassGroup, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Grup", group: "Aules" }
        calls:
            - [ setTemplate, [ edit, "::Admin/ClassGroup/edit.html.twig" ] ]
    admin.event:
        class: AppBundle\Admin\EventAdmin
        arguments: [ ~, AppBundle\Entity\Event, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Horari", group: "Aules" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Event/edit.html.twig" ] ]
    # billings
    admin.tariff:
        class: AppBundle\Admin\TariffAdmin
        arguments: [ ~, AppBundle\Entity\Tariff, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tarifa", group: "Facturació" }
    admin.invoice:
        class: AppBundle\Admin\InvoiceAdmin
        arguments: [ ~, AppBundle\Entity\Invoice, AppBundle:Admin\InvoiceAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Factura", group: "Facturació" }
        calls:
            - [ setTemplate, [ edit, "::Admin/Invoice/edit.html.twig" ] ]
    admin.billing.invoice_line:
        class: AppBundle\Admin\InvoiceLineAdmin
        arguments: [ ~, AppBundle\Entity\InvoiceLine, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Línies", group: "Facturació", show_in_dashboard: false }
    # services
    admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~, AppBundle\Entity\Service, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servei", group: "Serveis" }
    # contacts
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Messatge de contacte", group: "Contactes" }
    admin.newslettercontact:
        class: AppBundle\Admin\NewsletterContactAdmin
        arguments: [ ~, AppBundle\Entity\NewsletterContact, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Butlletí de contacte", group: "Contactes" }
    # admins
    admin.province:
        class: AppBundle\Admin\ProvinceAdmin
        arguments: [ ~, AppBundle\Entity\Province, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Administració" }
    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [ ~, AppBundle\Entity\City, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ciutat", group: "Administració" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Administració" }
    admin.bank:
        class: AppBundle\Admin\BankAdmin
        arguments: [ ~, AppBundle\Entity\Bank, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Bank", group: "Administració", show_in_dashboard: false }
# Block
    app.block.event_calendar:
        class: AppBundle\Block\EventCalendarBlock
        arguments:
            - "app.block.event_calendar"
            - "@templating"
        tags:
            - { name: sonata.block }
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments:
            - "@swiftmailer.mailer"
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments:
            - "@app.courier"
            - "@twig"
            - "%mailer_destination%"
            - "%mailer_url_base%"
# Factory
    app.event_transformer_factory:
        class: AppBundle\Service\EventTrasnformerFactoryService
        arguments:
            - "@router"
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.authorization_checker"
            - "@security.token_storage"
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: top }
# Listeners
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "presta.sitemap.listener" }
    app.event_fullcalendar:
        class: AppBundle\Listener\FullCalendarListener
        arguments:
            - "@app.event_repository"
            - "@app.event_transformer_factory"
        tags:
            - { name: "kernel.event_listener", event: "fullcalendar.set_data", method: "loadData" }
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
# Mailchimp Manager
    app.mailchimp_manager:
        class: AppBundle\Manager\MailchimpManager
        arguments:
            - "@app.notification"
            - "%mailchimp_api_key%"
# Generate Invoice Form Manager
    app.generate_invoice_form_manager:
        class: AppBundle\Manager\GenerateInvoiceFormManager
        arguments:
            - "@app.student_repository"
# PDF service builders
    app.base_tcpdf:
        class: AppBundle\Pdf\BaseTcpdf
        arguments:
            - "@templating.helper.assets"
            - "@translator.default"
    app.student_image_rights_pdf_builder:
        class: AppBundle\Service\StudentImageRightsPdfService
        arguments:
            - "@white_october.tcpdf"
            - "@templating.helper.assets"
            - "@translator.default"
            - "%project_web_title%"
    app.sepa_agreement_pdf_builder:
        class: AppBundle\Service\SepaAgreementPdfService
        arguments:
            - "@white_october.tcpdf"
            - "@templating.helper.assets"
            - "@translator.default"
            - "%project_web_title%"
            - "%boss_name%"
    app.invoice_pdf_builder:
        class: AppBundle\Service\InvoicePdfBuilderService
        arguments:
            - "@white_october.tcpdf"
            - "@templating.helper.assets"
            - "@translator.default"
# Repository
    app.bank_repository:
        class: AppBundle\Repository\BankRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Bank"
    app.parent_repository:
        class: AppBundle\Repository\PersonRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Person"
    app.city_repository:
        class: AppBundle\Repository\CityRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:City"
    app.province_repository:
        class: AppBundle\Repository\ProvinceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Province"
    app.teacher_repository:
        class: AppBundle\Repository\TeacherRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Teacher"
    app.teacher_absence_repository:
        class: AppBundle\Repository\TeacherAbsenceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:TeacherAbsence"
    app.student_repository:
        class: AppBundle\Repository\StudentRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Student"
    app.event_repository:
        class: AppBundle\Repository\EventRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Event"
    app.class_group_repository:
        class: AppBundle\Repository\ClassGroupRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:ClassGroup"
    app.tariff_repository:
        class: AppBundle\Repository\TariffRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Tariff"
    app.invoice_repository:
        class: AppBundle\Repository\InvoiceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - "AppBundle:Invoice"
