imports:
    - { resource: admins.yml }
    - { resource: repositories.yml }

services:
# Template Blocks
    app.block.event_calendar:
        class: AppBundle\Block\EventCalendarBlock
        arguments:
            - "app.block.event_calendar"
            - "@templating"
        tags:
            - { name: sonata.block }
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments:
            - "@swiftmailer.mailer"
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments:
            - "@app.courier"
            - "@twig"
            - "%mailer_destination%"
            - "%mailer_url_base%"
# Factories
    app.event_transformer_factory:
        class: AppBundle\Service\EventTrasnformerFactoryService
        arguments:
            - "@router"
    app.highchart_factory_service:
        class: AppBundle\Service\ChartsFactoryService
        arguments:
            - "@app.invoice_repository"
# Menus
    app.backend_top_nav_menu_builder:
        class: AppBundle\Menu\BackendTopNavMenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.token_storage"
            - "@app.contact_message_repository"
    app.backend_top_nav_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.backend_top_nav_menu_builder", createTopNavMenu ]
        tags:
            - { name: knp_menu.menu, alias: backend_top_nav_menu }
    app.backend_invoice_menu_builder:
        class: AppBundle\Menu\BackendInvoiceMenuBuilder
        arguments:
            - "@knp_menu.factory"
    app.backend_invoice_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.backend_invoice_menu_builder", createSideMenu ]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: backend_invoice_menu }
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@security.authorization_checker"
            - "@security.token_storage"
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: top }
# Listeners
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "presta.sitemap.listener" }
    app.event_fullcalendar:
        class: AppBundle\Listener\FullCalendarListener
        arguments:
            - "@app.event_repository"
            - "@app.teacher_absence_repository"
            - "@app.event_transformer_factory"
        tags:
            - { name: "kernel.event_listener", event: "fullcalendar.set_data", method: "loadData" }
# Twig Extensions
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        arguments:
            - "@app.smart_assets_helper"
            - "@app.receipt_manager"
            - "@translator"
        tags:
            - { name: twig.extension }
# Managers
    app.smart_assets_helper:
        class: AppBundle\Service\SmartAssetsHelperService
        arguments:
            - "@kernel"
            - "%mailer_url_base%"
    app.mailchimp_manager:
        class: AppBundle\Manager\MailchimpManager
        arguments:
            - "@app.notification"
            - "%mailchimp_api_key%"
    app.receipt_manager:
        class: AppBundle\Manager\ReceiptManager
        arguments:
            - "@app.invoice_repository"
    app.event_manager:
        class: AppBundle\Manager\EventManager
    app.generate_receipt_form_manager:
        class: AppBundle\Manager\GenerateReceiptFormManager
        arguments:
            - "@monolog.logger.email"
            - "@kernel"
            - "@doctrine.orm.entity_manager"
            - "@translator.default"
            - "@app.student_repository"
            - "@app.event_repository"
            - "@app.tariff_repository"
            - "@app.receipt_repository"
    app.generate_invoice_form_manager:
        class: AppBundle\Manager\GenerateInvoiceFormManager
        arguments:
            - "@monolog.logger.email"
            - "@kernel"
            - "@doctrine.orm.entity_manager"
            - "@translator.default"
            - "@app.student_repository"
            - "@app.event_repository"
            - "@app.tariff_repository"
            - "@app.invoice_repository"
# PDF Builders
    app.base_tcpdf:
        class: AppBundle\Pdf\BaseTcpdf
        arguments:
            - "@app.smart_assets_helper"
    app.student_image_rights_pdf_builder:
        class: AppBundle\Pdf\StudentImageRightsBuilderPdf
        arguments:
            - "@white_october.tcpdf"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "%project_web_title%"
    app.sepa_agreement_pdf_builder:
        class: AppBundle\Pdf\SepaAgreementBuilderPdf
        arguments:
            - "@white_october.tcpdf"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "%project_web_title%"
            - "%boss_name%"
    app.receipt_pdf_builder:
        class: AppBundle\Pdf\ReceiptBuilderPdf
        arguments:
            - "@white_october.tcpdf"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "%project_web_title%"
            - "%boss_name%"
            - "%boss_dni%"
            - "%boss_address%"
            - "%boss_city%"
            - "%iban_business%"
            - "%locale%"
    app.invoice_pdf_builder:
        class: AppBundle\Pdf\InvoiceBuilderPdf
        arguments:
            - "@white_october.tcpdf"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "%project_web_title%"
            - "%boss_name%"
            - "%boss_dni%"
            - "%boss_address%"
            - "%boss_city%"
            - "%iban_business%"
            - "%locale%"
# SEPA
    app.xml_sepa_builder:
        class: AppBundle\Service\XmlSepaBuilderService
        arguments:
            - "@app.spanish_sepa_helper"
            - "%boss_name%"
            - "%boss_dni%"
            - "%iban_business%"
            - "%bic_number%"
    app.spanish_sepa_helper:
        class: AppBundle\Service\SpanishSepaHelperService
# Forms
    app.form.type.generate_receipt:
        class: AppBundle\Form\Type\GenerateReceiptType
        arguments:
            - "@router.default"
        tags:
            - { name: form.type }
    app.form.type.generate_invoice:
        class: AppBundle\Form\Type\GenerateInvoiceType
        arguments:
            - "@router.default"
        tags:
            - { name: form.type }
    app.form.type.event:
        class: AppBundle\Form\Type\EventType
        arguments:
            - "@app.teacher_repository"
            - "@app.class_group_repository"
            - "@app.student_repository"
            - "@app.event_manager"
        tags:
            - { name: form.type }
    app.form.type.event_batch_remove:
        class: AppBundle\Form\Type\EventBatchRemoveType
        arguments:
            - "@app.event_manager"
        tags:
            - { name: form.type }
