services:
# Sonata Admin
    admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [ ~ , AppBundle\Entity\Teacher, ~ , "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Teacher", group: "Teachers" }
    admin.student:
        class: AppBundle\Admin\StudentAdmin
        arguments: [ ~ , AppBundle\Entity\Student, AppBundle:Admin\StudentAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Student", group: "Students" }
        calls:
            - [ setTemplate, [edit, "::Admin/Student/edit.html.twig"]]
    admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~ , AppBundle\Entity\Service, ~ , "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Service", group: "Services" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "User", group: "Administration" }
    admin.contactmessage:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Contact Message", group: "Contacts" }
    admin.newslettercontact:
        class: AppBundle\Admin\NewsletterContactAdmin
        arguments: [ ~, AppBundle\Entity\NewsletterContact, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Newsletter Contact ", group: "Contacts" }
    admin.province:
        class: AppBundle\Admin\ProvinceAdmin
        arguments: [ ~, AppBundle\Entity\Province, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Province", group: "Administration" }
    admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [ ~, AppBundle\Entity\City, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "City", group: "Administration" }
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@security.token_storage" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
# Sitemap
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments: [ "@router", "@doctrine.orm.entity_manager" ]
        tags: [ { name: "presta.sitemap.listener" } ]
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
# Mailchimp Manager
    app.mailchimp_manager:
        class: AppBundle\Manager\MailchimpManager
        arguments: [ "@app.notification", "%mailchimp_api_key%" ]

# PDF service builders
    app.base_tcpdf:
        class: AppBundle\Pdf\BaseTcpdf
        arguments:
            - "@templating.helper.assets"
            - "@translator.default"
    app.student_image_rights_pdf_builder:
        class: AppBundle\Service\StudentImageRightsPdfService
        arguments:
            - "@white_october.tcpdf"
            - "@templating.helper.assets"
            - "@translator.default"
            - "%project_web_title%"
    app.sepa_agreement_pdf_builder:
        class: AppBundle\Service\SepaAgreementPdfService
        arguments:
            - "@white_october.tcpdf"
            - "@templating.helper.assets"
            - "@translator.default"
            - "%project_web_title%"
            - "%boss_name%"
