services:
# Sonata Admin
    admin.teacher:
        class: AppBundle\Admin\TeacherAdmin
        arguments: [ ~ , AppBundle\Entity\Teacher, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Teacher", group: "Teachers" }
    admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~ , AppBundle\Entity\Service, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Service", group: "Services" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Usuaris" }
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
