# Sonata Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list: ~
        sonata.block.service.text:     ~
        app.block.event_calendar:      ~

# Sonata User
sonata_user:
    security_acl: true
    manager_type: orm

# Admin
sonata_admin:
    title: "%project_web_title%"
    title_logo: "/bundles/app/img/login-logo.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout:     "::Admin/layout.html.twig"
        edit:       "::Admin/edit.html.twig"
        show:       "::Admin/show.html.twig"
        dashboard:  "::Admin/dashboard.html.twig"
    dashboard:
        groups:
            Alumnes:
                icon: "<i class='fa fa-graduation-cap'></i>"
            Professors:
                icon: "<i class='fa fa-user'></i>"
            Aules:
                icon: "<i class='fa fa-window-maximize'></i>"
            Facturaci贸:
                icon: "<i class='fa fa-eur'></i>"
                provider: "backend_invoice_menu"
                roles: [ "ROLE_ADMIN" ]
            Serveis:
                icon: "<i class='fa fa-list-ul'></i>"
            Contactes:
                icon: "<i class='fa fa-envelope'></i>"
            Configuraci贸:
                icon: "<i class='fa fa-cogs'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: "col-xs-12"
                settings:
                    content: >
                        <h1 style="margin-top:0">%project_backend_title%</h1>
            -
                position: top
                type: app.block.event_calendar
                class: "col-xs-12"
                roles: [ "ROLE_MANAGER" ]
#            -
#                position: top
#                type: sonata.admin.block.admin_list
#                class: "col-md-6 col-lg-4"
#                settings:
#                    groups: [ Alumnes, Professors ]
#            -
#                position: top
#                type: sonata.admin.block.admin_list
#                class: "col-md-6 col-lg-4"
#                settings:
#                    groups: [ Aules, Facturaci贸 ]
#            -
#                position: top
#                type: sonata.admin.block.admin_list
#                class: "col-md-6 col-lg-4"
#                settings:
#                    groups: [ Serveis, Contactes, Administraci贸 ]
