# Sonata Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:  ~
        sonata.block.service.text:      ~

# Sonata User
sonata_user:
    security_acl: true
    manager_type: orm

# Admin
sonata_admin:
    title: "%project_web_title%"
    title_logo: "/bundles/app/img/login-logo.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
    dashboard:
        groups:
            Professors:
                icon: "<i class='fa fa-users'></i>"
            Alumnes:
                icon: "<i class='fa fa-graduation-cap'></i>"
            Aules:
                icon: "<i class='fa fa-book'></i>"
            Serveis:
                icon: "<i class='fa fa-list-ol'></i>"
            Contactes:
                icon: "<i class='fa fa-envelope'></i>"
            Administration:
                label: "Administració"
                icon: "<i class='fa fa-briefcase'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: "col-xs-12"
                settings:
                    content: >
                        <h1 style="margin-top:0">%project_backend_title%</h1>
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-6 col-lg-4"
                settings:
                    groups: [ Professors, Alumnes ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-6 col-lg-4"
                settings:
                    groups: [ Aules, Serveis ]
#            -
#                position: top
#                type: sonata.admin.block.admin_list
#                class: "col-md-6 col-lg-4"
#                settings:
#                    groups: [ Serveis, Contactes ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-6 col-lg-4"
                settings:
                    groups: [ Contactes, Administration ]
